data:
  train_data_path: "./data/eng2kor.json"
  val_data_path: "./data/eng2kor.json"

model:
  max_seq_length: 15
  num_layers: 6
  num_heads: 8
  d_ff: 2048
  d_model: 512
  drop_prob: 0.1

train:
  batch_size: 2

optimizer:
  init_lr: 1e-5
  factor: 0.9
  adam_eps: 5e-9
  patience: 10
  warmup: 100
  epoch: 1
  clip: 1.0
  weight_decay: 5e-4
  inf: float('inf')
#
#logging:
#  log_dir: "logs/"
#  checkpoint_dir: "checkpoints/"